### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jjtParadox** [Valiec/DeeperCaves#23]
Is this code under a license? If there's no official one, what are the general rules of attribution, modification, and redistribution?

**Comment by Valiec** [comment]
Sorry, but I haven't chosen a license yet nor written up specific rules, but here are some general guidelines until then:

1) You *are* allowed to modify the source code.

2) In modified and unmodified versions, please credit me (Valiec2019) (as well as yourself for a modified version).

3) For modified versions, please say somewhere that they are modified (to make dealing with error reports easier for me, because I can tell whether it is my version or a modified one).

4) Before publishing a modified or unmodified jar file (linking to my original download link is not "publishing" and this does not apply to it), please ask permission (this is more to handle a bunch of different versions suddenly popping up, all slightly different).

**Comment by Valiec** [comment]
I've changed my mind about these rules, this is now under the MIT License.
